module:
  name: poi-ui
  path: poi-ui
  description: React web dashboard for POI - shows workspace status, command suggestions, command previews, reports, and recipes
  status: active

tags:
  - react
  - typescript
  - web-ui
  - mui
  - zustand
  - polling
  - vite
  - dashboard

dependencies:
  uses:
    - poi (API server)
    - react
    - "@mui/material"
    - zustand
    - react-markdown
    - vite
  used_by: []

entities:
  - name: ApiClient
    file: src/api/client.ts
    tags:
      - api
      - http
    description: Typed REST client for POI API endpoints (session, modules, suggestions, preview, recipes, reports)

  - name: usePolling
    file: src/api/usePolling.ts
    tags:
      - polling
      - hook
      - state
    description: Periodic REST polling hook that fetches /api/session and populates session data store

  - name: useSessionDataStore
    file: src/api/usePolling.ts
    tags:
      - state
      - zustand
    description: Zustand store holding server data (status, suggestions, workspace) populated by polling

  - name: usePollingStore
    file: src/api/usePolling.ts
    tags:
      - state
      - zustand
    description: Zustand store for connection state and notifications (UI-local)

  - name: useDrawer
    file: src/hooks/useDrawer.ts
    tags:
      - state
      - drawer
      - hook
    description: Zustand store for drawer open/close state, content mode, and viewer data

  - name: AppShell
    file: src/components/AppShell.tsx
    tags:
      - layout
      - component
    description: Main layout with responsive command panel and content drawer

  - name: CommandPanel
    file: src/components/CommandPanel.tsx
    tags:
      - component
      - panel
    description: Left panel with header, status block, suggestions block, command input, and menus for modules/recipes/reports

  - name: ContentDrawer
    file: src/components/ContentDrawer.tsx
    tags:
      - component
      - drawer
    description: Right drawer routing to viewers based on mode (modules, module, report, command-preview, recipes, output)

  - name: CommandInput
    file: src/components/CommandInput.tsx
    tags:
      - component
      - input
    description: Command entry with autocomplete for commands and @module references

  - name: CommandPreview
    file: src/viewers/CommandPreview.tsx
    tags:
      - component
      - viewer
    description: Sectioned command expansion viewer with provenance headers, token stats, and clipboard copy

  - name: SuggestionsBlock
    file: src/blocks/SuggestionsBlock.tsx
    tags:
      - component
      - suggestions
    description: Displays ranked command suggestions; click triggers command preview in drawer

  - name: StatusBlock
    file: src/blocks/StatusBlock.tsx
    tags:
      - component
      - status
    description: Documentation coverage bar with documented/stale/gap chips and clickable module links

  - name: RecipesViewer
    file: src/viewers/RecipesViewer.tsx
    tags:
      - component
      - viewer
    description: Lists configured multi-step workflow recipes with step details

  - name: ReportViewer
    file: src/viewers/ReportViewer.tsx
    tags:
      - component
      - viewer
    description: Renders health, coverage, deps, tags, gotchas, and entities reports

  - name: createAppTheme
    file: src/theme/index.ts
    tags:
      - theme
      - styling
    description: MUI theme factory with GitHub-inspired dark/light modes

gotchas:
  - id: vite-proxy-required
    tags:
      - api
      - cors
      - vite
    summary: API calls use relative URLs that require Vite proxy configuration
    section: Vite Proxy Required for API Calls

  - id: go-null-slices
    tags:
      - api
      - go
      - json
    summary: Go nil slices marshal as JSON null, not []; use ?? [] in UI code
    section: Go API Returns null for Empty Slices

  - id: polling-vs-session-store
    tags:
      - zustand
      - state
      - architecture
    summary: usePollingStore holds UI-local state; useSessionDataStore holds server data from polling
    section: Polling Store vs Session Data Store

  - id: drawer-mode-fields
    tags:
      - drawer
      - state
    summary: Each drawer mode expects specific fields; mismatched mode/fields shows "No content selected"
    section: Drawer Content Must Match Mode

  - id: focus-module-default
    tags:
      - commands
      - state
    summary: Commands without @module use the focus module as default; clicking suggestions sets focus
    section: Focus Module Affects Commands
